-- PostgreSQL database dump
--

-- Dumped from database version 15.8
-- Dumped by pg_dump version 16.9 (Ubuntu 16.9-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: configuration; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.configuration (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    user_id uuid NOT NULL,
    resume json NOT NULL,
    name character varying NOT NULL
);


ALTER TABLE public.configuration OWNER TO postgres;

--
-- Name: configuration_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.configuration ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.configuration_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: configuration configuration_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.configuration
    ADD CONSTRAINT configuration_pkey PRIMARY KEY (id);


--
-- Name: configuration configuration_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.configuration
    ADD CONSTRAINT configuration_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id);


--
-- Name: configuration; Type: ROW SECURITY; Schema: public; Owner: postgres
--

ALTER TABLE public.configuration ENABLE ROW LEVEL SECURITY;

--
-- Name: TABLE configuration; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.configuration TO anon;
GRANT ALL ON TABLE public.configuration TO authenticated;
GRANT ALL ON TABLE public.configuration TO service_role;


--
-- Name: SEQUENCE configuration_id_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.configuration_id_seq TO anon;
GRANT ALL ON SEQUENCE public.configuration_id_seq TO authenticated;
GRANT ALL ON SEQUENCE public.configuration_id_seq TO service_role;


--
-- PostgreSQL database dump complete
--