create table "public"."userprofile" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "resume" jsonb,
    "settings" jsonb not null default '{}'::jsonb,
    "user_id" uuid
);


alter table "public"."userprofile" enable row level security;

CREATE UNIQUE INDEX userprofile_pkey ON public.userprofile USING btree (id);

alter table "public"."userprofile" add constraint "userprofile_pkey" PRIMARY KEY using index "userprofile_pkey";

alter table "public"."userprofile" add constraint "userprofile_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) not valid;

alter table "public"."userprofile" validate constraint "userprofile_user_id_fkey";

grant delete on table "public"."userprofile" to "anon";

grant insert on table "public"."userprofile" to "anon";

grant references on table "public"."userprofile" to "anon";

grant select on table "public"."userprofile" to "anon";

grant trigger on table "public"."userprofile" to "anon";

grant truncate on table "public"."userprofile" to "anon";

grant update on table "public"."userprofile" to "anon";

grant delete on table "public"."userprofile" to "authenticated";

grant insert on table "public"."userprofile" to "authenticated";

grant references on table "public"."userprofile" to "authenticated";

grant select on table "public"."userprofile" to "authenticated";

grant trigger on table "public"."userprofile" to "authenticated";

grant truncate on table "public"."userprofile" to "authenticated";

grant update on table "public"."userprofile" to "authenticated";

grant delete on table "public"."userprofile" to "service_role";

grant insert on table "public"."userprofile" to "service_role";

grant references on table "public"."userprofile" to "service_role";

grant select on table "public"."userprofile" to "service_role";

grant trigger on table "public"."userprofile" to "service_role";

grant truncate on table "public"."userprofile" to "service_role";

grant update on table "public"."userprofile" to "service_role";


